### PR TITLE
Update CRDs using fetch-crds.sh

### PR DESCRIPTION
**Pull request by JohnNiang**
### What this PR does

Update application.gitops.kubesphere.io CRD using fetch-crds.sh. See 
- https://github.com/kubesphere/ks-devops/pull/502

for more.

/cc @kubesphere-sigs/sig-devops 
/kind chore

### CODE REVIEW

**Comment by JohnNiang** [comment]
/hold

Wait util https://github.com/kubesphere/ks-devops/pull/505 is merged.

**Comment by JohnNiang** [comment]
/hold

Wait util https://github.com/kubesphere/ks-devops/pull/505 is merged.

**Review by LinuxSuRen — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
