### PR TITLE
Reformat yaml config item in pod template

### PR DESCRIPTION
**Pull request by JohnNiang**
### What this PR dose?

Reformat yaml config item in pod template.

### Why we need it?

Before this, the yaml config items were formatted ugly, non-configurable and unreadable. But now, everything would be okay.

### How do I format them?

To open developer tools for your browser, please press `F12` and choose console tab. Then input JS code: `console.log("unformatted text")` and press `Enter`. Please see an example below:

image

/kind chore

### CODE REVIEW

**Comment by JohnNiang** [comment]
In order to avoid unnecessary problems during the v3.2.0 release time period. I'll hold this PR until KubeSphere v3.2.0 is ready.
/hold

**Comment by JohnNiang** [comment]
Since that [KubeSphere 3.2.0](https://github.com/kubesphere/kubesphere/releases/tag/v3.2.0) has been released and announced, we can continue to push this forward.

/unhold

**Comment by LinuxSuRen** [comment]
> /ping @kubesphere-sigs/sig-devops

I do my best to review this tomorrow. Thanks for the reminder.

**Review by LinuxSuRen — COMMENTED** [review]
/lgtm

**Pull request merged**
