### PR TITLE
Prepend 'http://' for 'unclassified.location.url' in CasC configuration

### PR DESCRIPTION
**Pull request by 123liubao**
Fix: https://github.com/kubesphere/ks-devops/issues/440

### CODE REVIEW

**Comment by 123liubao** [comment]
/assign @linuxsuren 
Hello, I don't know if I updated it correctly, please take a look.

**Comment by LinuxSuRen** [comment]
thanks for your time. @123liubao

**Review by LinuxSuRen — COMMENTED** [review]
/lgtm

**Review by JohnNiang — COMMENTED** [review]
Thanks for your effort! I will test it manually soon.

**Review by JohnNiang — APPROVED** [review]
/lgtm
/approve

I could confirm the issue would be fixed by this PR, please see the CasC after reloading existing CasC.
image

**Pull request merged**
